### ISSUE TITLE
Ktor plugin is obsolete

### ISSUE THREAD

**Issue by FlyingBackdoor** [philipplackner/KtorNoteServer#1]
I just started the course and I found that ktor plugin is no longer supported in IntelliJ IDEA.

https://plugins.jetbrains.com/plugin/10823-ktor-obsolete-
> _"Please note that this plugin is being replaced and will be not supported beyond Ktor 1.5.3"_

Can you please update the content or tell me how to get started now.

**Comment by philipplackner** [comment]
You can still use the plugin. It sounds like they will replace it soon with
a new one, but I can't find any replacement yet. You don't need the plugin
to develop or run ktor applications, it's just a little help to create a
ktor project.

**Comment by FlyingBackdoor** [comment]
New Plugin is live on IDE marketplace https://plugins.jetbrains.com/plugin/16008-ktor
